project:
  type: website
  output-dir: docs

website:
  title: "吾輩は猫でR"
  navbar:
    left:
      - href: ggtree.qmd
        text: ggtree
      - href: quarto.qmd
        text: Quarto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

